package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Android'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Android")) {
    params {
        add {
            param("JAVA_HOME", "%env.JDK_1_8_x64%")
        }
        add {
            param("env.JAVA_HOME", "%env.JDK_1_8_x64%")
        }
    }
}
