package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'AndroidBuild'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("AndroidBuild")) {
    params {
        add {
            text("habr-client-token", "85cab69095196f3.89453480", label = "habr-client-token", description = "Contains a client token for Habr", display = ParameterDisplay.HIDDEN, readOnly = true, allowEmpty = false)
        }
    }
}
