package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*
import jetbrains.buildServer.configs.kotlin.v2019_2.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the vcsRoot with id = 'MetadataVcsRoot'
accordingly, and delete the patch script.
*/
changeVcsRoot(RelativeId("MetadataVcsRoot")) {
    val expected = GitVcsRoot({
        id("MetadataVcsRoot")
        name = "Metadata"
        url = "ssh://git@git.jetbrains.space/makentoshe/habrachan/Habrachan-metadata.git"
        authMethod = uploadedKey {
            uploadedKey = "id_rsa"
            passphrase = "credentialsJSON:211c06d0-dd07-42a8-8344-211453523bdc"
        }
        param("useAlternates", "true")
    })

    check(this == expected) {
        "Unexpected VCS root settings"
    }

    (this as GitVcsRoot).apply {
        branch = "master"
        checkoutPolicy = GitVcsRoot.AgentCheckoutPolicy.NO_MIRRORS
    }

}
